framework:
    default_locale: it
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - it
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
